/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#006c49",
        "on-primary": "#ffffff",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "inverse-primary": "#4edea3",
        secondary: "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9ff",
        "on-background": "#121c2a",
        surface: "#f9f9ff",
        "on-surface": "#121c2a",
        "surface-variant": "#d9e3f7",
        "on-surface-variant": "#3c4a42",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff3ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fd",
        "surface-container-highest": "#d9e3f7",
        outline: "#6c7a71",
        "outline-variant": "#bbcabf",
      },
      fontFamily: { sans: ["Inter", "sans-serif"] },
      maxWidth: { "max-width-desktop": "1280px" },
      spacing: { xs: "0.5rem", sm: "0.75rem", base: "1rem", md: "1.5rem", lg: "2rem", xl: "3rem", "margin-desktop": "2.5rem" },
    },
  },
  plugins: [],
}
